name: Despliegue a produccion

on:
  push:
    branches:
      - main # Se ejecuta en cada push a la rama main

jobs:
  tests: # Job para ejecutar pruebas
    runs-on: ubuntu-latest # Crea un entorno virtual en Ubuntu
    steps:
      - name: Checkout código # Clona el repositorio en el entorno virtual
        uses: actions/checkout@v4 # Usa una acción de GitHub

      - name: Instalar Node.js # Instala Node.js en el entorno virtual
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependencias # Instala las dependencias del proyecto
        run: npm install

      - name: Ejecutar pruebas # Ejecuta las pruebas del proyecto
        run: npm test

  # Cuidado: Las conecciones SSH y OpenVPN pueden ser peligrosas si no se protejen correctamente.
  # Asegúrate que todas las credenciales estan protegidas con el uso de secretos de repositorio.
  # EN NINGUN CASO SE DEBEN DEJAR CREDENCIALES EXPUESTAS EN ESTE ARCHIVO NI EN NINGUN OTRO.
  # Si no sabes como proteger tus credenciales, consulta la documentacion de GitHub o pregunta a un profesor.
  # https://docs.github.com/es/actions/security-guides/encrypted-secrets

  deploy: # Job para desplegar el proyecto
    needs: tests # Este job depende del job de pruebas, por lo que no se ejecutará si el job de pruebas falla
    runs-on: ubuntu-latest
    steps:
      - name: Instalar dependencias (OpenVPN, SSH y sshpass)
        run: |
          sudo apt update -qq > /dev/null 2>&1
          sudo apt install -y -qq openvpn openvpn-systemd-resolved openssh-client sshpass > /dev/null 2>&1

      - name: Crear archivo de configuración OpenVPN # Crea el archivo de configuración OpenVPN en memoria
        run: |
          echo "${{ secrets.OPENVPN_CONFIG }}" > /dev/shm/face-ubb.ovpn
          echo -e "${{ secrets.OPENVPN_USERNAME }}\n${{ secrets.OPENVPN_PASSWORD }}" > /dev/shm/openvpn_auth.txt

      - name: Conexion a la VPN de la UBB # Conecta a la VPN de la UBB
        timeout-minutes: 2 # Establece un timeout de 2 minutos para la conexión
        run: |
          sudo openvpn \
            --config /dev/shm/face-ubb.ovpn \
            --auth-user-pass /dev/shm/openvpn_auth.txt \
            --verb 4 \
            --log /dev/stdout \
            &
          sleep 10 # Espera 10 segundos para que la conexión se establezca

      - name: Eliminar archivo de configuración OpenVPN # Limpia el archivo de configuración
        run: |
          rm -f /dev/shm/face-ubb.ovpn
          rm -f /dev/shm/openvpn_auth.txt

      - name: Conexión SSH y Despliegue
        timeout-minutes: 1
        run: |
          sshpass -p "${{ secrets.PROD_PASSWORD }}" ssh \
            -o StrictHostKeyChecking=no \
            -p ${{ secrets.PROD_PORT }} \
            ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} << 'EOF'
              cd cicd/EICRV
              git fetch origin main
              git reset --hard origin/main
              npm install
              pm2 restart eicrv
          EOF
