name: Despliegue a produccion

on:
  push:
    branches:
      - main # Se ejecuta en cada push a la rama main

jobs:
  tests: # Job para ejecutar pruebas
    runs-on: ubuntu-latest # Crea un entorno virtual en Ubuntu
    steps:
      - name: Checkout código # Clona el repositorio en el entorno virtual
        uses: actions/checkout@v4 # Usa una acción de GitHub

      - name: Instalar Node.js # Instala Node.js en el entorno virtual
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependencias # Instala las dependencias del proyecto
        run: npm install

      - name: Ejecutar pruebas # Ejecuta las pruebas del proyecto
        run: npm test

  # Cuidado: Las conecciones SSH y OpenVPN pueden ser peligrosas si no se protejen correctamente.
  # Asegúrate que todas las credenciales estan protegidas con el uso de secretos de repositorio.
  # EN NINGUN CASO SE DEBEN DEJAR CREDENCIALES EXPUESTAS EN ESTE ARCHIVO NI EN NINGUN OTRO.
  # Si no sabes como proteger tus credenciales, consulta la documentacion de GitHub o pregunta a un profesor.
  # https://docs.github.com/es/actions/security-guides/encrypted-secrets

  deploy: # Job para desplegar el proyecto
    needs: tests # Este job depende del job de pruebas, por lo que no se ejecutará si el job de pruebas falla
    runs-on: ubuntu-latest
    steps:
      - name: Instalar OpenVPN # Instala OpenVPN en el entorno virtual
        run: |
          sudo apt update -qq > /dev/null 2>&1
          sudo apt install -y -qq openvpn openvpn-systemd-resolved > /dev/null 2>&1

      - name: Crear archivo de configuración OpenVPN # Crea el archivo de configuración OpenVPN
        run: echo "${{ secrets.OPENVPN_CONFIG }}" > face-ubb.ovpn

      - name: Conexion a la VPN de la UBB # Conecta a la VPN de la UBB
        uses: kota65535/github-openvpn-connect-action@v3.0.0 # Usa una acción de GitHub creada por un usuario
        timeout-minutes: 3 # Tiempo máximo de espera para conectarse a la VPN
        with:
          config_file: face-ubb.ovpn # Nombre del archivo de configuración previamente creado
          username: ${{ secrets.OPENVPN_USERNAME }}
          password: ${{ secrets.OPENVPN_PASSWORD }}

      - name: Conexion SSH y Despliegue # Conecta por SSH al servidor y despliega el proyecto
        uses: appleboy/ssh-action@v1
        timeout-minutes: 3 # Tiempo máximo de espera para conectarse al servidor
        with: # Conexión SSH al servidor
          host: ${{ secrets.PROD_HOST }}
          port: ${{ secrets.PROD_PORT }}
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          script:
            | # Ejecuta el script de despliegue en el servidor. Se asume que el servidor fue iniciado al menos una vez.
            cd cicd/EICRV
            git fetch origin main
            git reset --hard origin/main
            npm install
            pm2 restart eicrv
